/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyPublicDecryptMultipleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "entropyOracle"
      | "entropyRequests"
      | "getEncryptedValue"
      | "getEntropyOracle"
      | "getTotalValues"
      | "isInitialized"
      | "isKeyInitialized"
      | "requestEntropy"
      | "storeAndMakePublic"
      | "storeAndMakePublicBatch"
      | "storeAndMakePublicBatchWithEntropy"
      | "storeAndMakePublicWithEntropy"
      | "totalValues"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntropyRequested"
      | "ValueMadePubliclyDecryptable"
      | "ValueStored"
      | "ValueStoredWithEntropy"
      | "ValuesStoredBatch"
      | "ValuesStoredBatchWithEntropy"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalValues",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isKeyInitialized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAndMakePublic",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAndMakePublicBatch",
    values: [BigNumberish[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAndMakePublicBatchWithEntropy",
    values: [BigNumberish[], BytesLike[], BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAndMakePublicWithEntropy",
    values: [BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalValues",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKeyInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAndMakePublic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAndMakePublicBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAndMakePublicBatchWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAndMakePublicWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValues",
    data: BytesLike
  ): Result;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueMadePubliclyDecryptableEvent {
  export type InputTuple = [key: BigNumberish];
  export type OutputTuple = [key: bigint];
  export interface OutputObject {
    key: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueStoredEvent {
  export type InputTuple = [key: BigNumberish, user: AddressLike];
  export type OutputTuple = [key: bigint, user: string];
  export interface OutputObject {
    key: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueStoredWithEntropyEvent {
  export type InputTuple = [
    key: BigNumberish,
    requestId: BigNumberish,
    user: AddressLike
  ];
  export type OutputTuple = [key: bigint, requestId: bigint, user: string];
  export interface OutputObject {
    key: bigint;
    requestId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValuesStoredBatchEvent {
  export type InputTuple = [keys: BigNumberish[], user: AddressLike];
  export type OutputTuple = [keys: bigint[], user: string];
  export interface OutputObject {
    keys: bigint[];
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValuesStoredBatchWithEntropyEvent {
  export type InputTuple = [
    keys: BigNumberish[],
    requestId: BigNumberish,
    user: AddressLike
  ];
  export type OutputTuple = [keys: bigint[], requestId: bigint, user: string];
  export interface OutputObject {
    keys: bigint[];
    requestId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyPublicDecryptMultiple extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyPublicDecryptMultiple;
  waitForDeployment(): Promise<this>;

  interface: EntropyPublicDecryptMultipleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEncryptedValue: TypedContractMethod<[key: BigNumberish], [string], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  getTotalValues: TypedContractMethod<[], [bigint], "view">;

  isInitialized: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  isKeyInitialized: TypedContractMethod<[key: BigNumberish], [boolean], "view">;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  storeAndMakePublic: TypedContractMethod<
    [key: BigNumberish, encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  storeAndMakePublicBatch: TypedContractMethod<
    [
      keys: BigNumberish[],
      encryptedInputs: BytesLike[],
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  storeAndMakePublicBatchWithEntropy: TypedContractMethod<
    [
      keys: BigNumberish[],
      encryptedInputs: BytesLike[],
      inputProofs: BytesLike[],
      requestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  storeAndMakePublicWithEntropy: TypedContractMethod<
    [
      key: BigNumberish,
      encryptedInput: BytesLike,
      inputProof: BytesLike,
      requestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  totalValues: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEncryptedValue"
  ): TypedContractMethod<[key: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalValues"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isKeyInitialized"
  ): TypedContractMethod<[key: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "storeAndMakePublic"
  ): TypedContractMethod<
    [key: BigNumberish, encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeAndMakePublicBatch"
  ): TypedContractMethod<
    [
      keys: BigNumberish[],
      encryptedInputs: BytesLike[],
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeAndMakePublicBatchWithEntropy"
  ): TypedContractMethod<
    [
      keys: BigNumberish[],
      encryptedInputs: BytesLike[],
      inputProofs: BytesLike[],
      requestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeAndMakePublicWithEntropy"
  ): TypedContractMethod<
    [
      key: BigNumberish,
      encryptedInput: BytesLike,
      inputProof: BytesLike,
      requestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalValues"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ValueMadePubliclyDecryptable"
  ): TypedContractEvent<
    ValueMadePubliclyDecryptableEvent.InputTuple,
    ValueMadePubliclyDecryptableEvent.OutputTuple,
    ValueMadePubliclyDecryptableEvent.OutputObject
  >;
  getEvent(
    key: "ValueStored"
  ): TypedContractEvent<
    ValueStoredEvent.InputTuple,
    ValueStoredEvent.OutputTuple,
    ValueStoredEvent.OutputObject
  >;
  getEvent(
    key: "ValueStoredWithEntropy"
  ): TypedContractEvent<
    ValueStoredWithEntropyEvent.InputTuple,
    ValueStoredWithEntropyEvent.OutputTuple,
    ValueStoredWithEntropyEvent.OutputObject
  >;
  getEvent(
    key: "ValuesStoredBatch"
  ): TypedContractEvent<
    ValuesStoredBatchEvent.InputTuple,
    ValuesStoredBatchEvent.OutputTuple,
    ValuesStoredBatchEvent.OutputObject
  >;
  getEvent(
    key: "ValuesStoredBatchWithEntropy"
  ): TypedContractEvent<
    ValuesStoredBatchWithEntropyEvent.InputTuple,
    ValuesStoredBatchWithEntropyEvent.OutputTuple,
    ValuesStoredBatchWithEntropyEvent.OutputObject
  >;

  filters: {
    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "ValueMadePubliclyDecryptable(uint256)": TypedContractEvent<
      ValueMadePubliclyDecryptableEvent.InputTuple,
      ValueMadePubliclyDecryptableEvent.OutputTuple,
      ValueMadePubliclyDecryptableEvent.OutputObject
    >;
    ValueMadePubliclyDecryptable: TypedContractEvent<
      ValueMadePubliclyDecryptableEvent.InputTuple,
      ValueMadePubliclyDecryptableEvent.OutputTuple,
      ValueMadePubliclyDecryptableEvent.OutputObject
    >;

    "ValueStored(uint256,address)": TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;
    ValueStored: TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;

    "ValueStoredWithEntropy(uint256,uint256,address)": TypedContractEvent<
      ValueStoredWithEntropyEvent.InputTuple,
      ValueStoredWithEntropyEvent.OutputTuple,
      ValueStoredWithEntropyEvent.OutputObject
    >;
    ValueStoredWithEntropy: TypedContractEvent<
      ValueStoredWithEntropyEvent.InputTuple,
      ValueStoredWithEntropyEvent.OutputTuple,
      ValueStoredWithEntropyEvent.OutputObject
    >;

    "ValuesStoredBatch(uint256[],address)": TypedContractEvent<
      ValuesStoredBatchEvent.InputTuple,
      ValuesStoredBatchEvent.OutputTuple,
      ValuesStoredBatchEvent.OutputObject
    >;
    ValuesStoredBatch: TypedContractEvent<
      ValuesStoredBatchEvent.InputTuple,
      ValuesStoredBatchEvent.OutputTuple,
      ValuesStoredBatchEvent.OutputObject
    >;

    "ValuesStoredBatchWithEntropy(uint256[],uint256,address)": TypedContractEvent<
      ValuesStoredBatchWithEntropyEvent.InputTuple,
      ValuesStoredBatchWithEntropyEvent.OutputTuple,
      ValuesStoredBatchWithEntropyEvent.OutputObject
    >;
    ValuesStoredBatchWithEntropy: TypedContractEvent<
      ValuesStoredBatchWithEntropyEvent.InputTuple,
      ValuesStoredBatchWithEntropyEvent.OutputTuple,
      ValuesStoredBatchWithEntropyEvent.OutputObject
    >;
  };
}
